version: "3.7"
services:
  api_public:
    image: node:latest
    container_name: api_order_dev
    networks:
      - dev-net
    ports:
      - "127.0.0.1:9301:9301"
      - "127.0.0.1:62000:62000"
    volumes:
      - ./:/api_order
    environment:
      ENV: local_dev
    working_dir: /api_order
    tty: true
    entrypoint: bash
    command: debug

networks:
  dev-net:
    external: true